spring:
  datasource:
    url: jdbc:postgresql://hopper.proxy.rlwy.net:11537/railway
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
      org.springdoc: DEBUG
      me.dio: DEBUG
